### ISSUE TITLE
how do i set newly created application credentials in peatio.env 

### ISSUE THREAD

**Issue by Jacob807** [rubykube/workbench#109]
Im confused on what command to put in docker/terminal to add the credentials too. I tried just "peatio.env" as the command and i was prompted with command not found as the response. If anyone one can help i would really appreciate it. 

Thanks

**Comment by ianeinser** [comment]
Hi @Jacob807 .. i advise you not to change anything yet.. just run 'make build' and 'make run' and see if you can manage to get the compilation done.. then you can play with some parameters by changing them.. i did some changes before compilation and spent almost 8 hours to figure out what went wrong.. got lessons learned

**Comment by Jacob807** [comment]
Thank You @ianeinser I really appreciate the help. By chance do you have a skype or anything else that I could contact you on for any further questions? 

Thank You, Again
