### ISSUE TITLE
Make run ERROR

### ISSUE THREAD

**Issue by ianeinser** [rubykube/workbench#113]
hi guys,

i got these errors when I run 'make run'. It seems like i cannot create database for peatio and barong

this is for peatio:
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "collation"=>"utf8_general_ci", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>"admin", "database"=>"workbench_development"}
rake aborted!
Mysql2::Error: Access denied for user 'root'@'172.18.0.8' (using password: YES)

this is for barong:

== Preparing database ==
Access denied for user 'root'@'172.18.0.8' (using password: YES)Please provide the root password for your MySQL installation
>admin
Access denied for user 'root'@'172.18.0.8' (using password: YES)
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "collation"=>"utf8_general_ci", "pool"=>5, "host"=>"db", "username"=>"root", "password"=>"admin", "database"=>"barong_development"}
rails aborted!
Mysql2::Error: Access denied for user 'root'@'172.18.0.8' (using password: YES)

Do I miss anything?

thanks

**Comment by ianeinser** [comment]
Here I am again..

i accidentally changed some parameters with 'changeme' . i removed the workbench directory and re git it and everything looks good now at the moment. The error is gone. Thanks @shal .

**Comment by AnkitRathore175** [comment]
Hello Everyone, 
I m getting same issue, could anyone point me to the right solutions, i tried with above solutions but not get succeed :(
Thanks in advance

**Comment by shal** [comment]
@AnkitRathore175 this issue is solved, just switch to latest commit of master branch :smile:

**Comment by AnkitRathore175** [comment]
Hi @shal 
Thanks for reply,
i m on master branch,
Are you referring to change branch of submodules?

**Comment by shal** [comment]
@AnkitRathore175  

- Stop your local mysql if it running, use one that in docker.
- Update submodules.
- Clean up your volumes.
- Try to start containers from scratch.

You're doing something, while everything works correctly for me.

**Comment by AnkitRathore175** [comment]
great it worked, i did like below-
took fresh clone of workbench
then run -
`docket volume prune`
`sudo service mysql stop`
`make update`
`make build`
`make run`
and i saw problem is resolved, 
Thanks @shal 
one query:- why do i needed to stop mysql, if i m not wrong then it is using my local resources(mysql, redis, etc..), right?
