### ISSUE TITLE
api/v1/sessions/generate_jwt returns error code 500

### ISSUE THREAD

**Issue by vyloy** [rubykube/workbench#118]
api/v1/sessions/generate_jwt returns error code 500

It can be reproduced by run the following test program:
https://github.com/vyloy/gocryptotrader/blob/master/exchanges/peatio/testdata/gentestdata.go

**Comment by shal** [comment]
Hello @vyloy,

Thank's, but this related to [peatio](https://github.com/rubykube/peatio), not workbench.
