### ISSUE TITLE
Documentation: Starting Frontend 

### ISSUE THREAD

**Issue by asheeshmathur** [rubykube/workbench#119]
Current README.md file,   states "Simply start your local server. Now you're able to log in with your local Barong and Peatio.". However it is silent about what  actual steps to be followed.

Suggest following two points be added to make it explicit.

1. Visit URL  http://auth,wb.local , login using  a/c created be Barong above (admin@barong.io / Qwerty123).

2. Once login is successful, visit URL http://api.wb.local,  this will present Peatio screen.

**Comment by shal** [comment]
Thanks for suggestion @asheeshmathur!
