### ISSUE TITLE
Error During Make Run

### ISSUE THREAD

**Issue by laugh26** [rubykube/workbench#132]
ERROR: Service 'peatio' failed to build: The command '/bin/sh -c ./bin/init_config   && chmod +x ./bin/logger   && bundle exec rake tmp:create yarn:install assets:precompile' returned a non-zero code: 1
Makefile:22: recipe for target 'daemons' failed
make: *** [daemons] Error 1
how do i set correctly the database and this particular error
solved

**Comment by AkashiHidaka** [comment]
Hello
I have same issue and how to solve of it?
Can you help me of the reason?
