### ISSUE TITLE
Make daemons failed

### ISSUE THREAD

**Issue by ZSmartDev** [rubykube/workbench#142]
IMAGE: https://imgur.com/a/IEjha1i

CODE: 

> Starting workbench_proxy_1 ... done
> Starting workbench_barong_1 ... done
> Starting workbench_peatio_1 ... done
> Starting workbench_slave_book_1 ...
> Starting workbench_slave_book_1              ... done
> Starting workbench_deposit_collection_1      ... done
> Starting workbench_deposit_collection_fees_1 ... done
> Starting workbench_matching_1                ... done
> Starting workbench_market_ticker_1           ...
> Starting workbench_market_ticker_1           ... done
> Starting workbench_trade_executor_1          ...
> Starting workbench_trade_executor_1          ... done
> Starting workbench_pusher_member_1           ... done
> Starting workbench_withdraw_audit_1          ... done
> Starting workbench_withdraw_coin_1           ... done
> Starting workbench_deposit_coin_address_1    ...
> WARNING: Connection pool is full, discarding connection: localhost
> 
> ERROR: for workbench_pusher_market_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for workbench_blockchain_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for workbench_deposit_coin_address_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for workbench_order_processor_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for deposit_coin_address  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for pusher_market  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for blockchain  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for order_processor  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
> Makefile:22: recipe for target 'daemons' failed
> make: *** [daemons] Error 1
> Makefile:22: recipe for target 'daemons' failed
> make: *** [daemons] Error 1

Thank you for your support!

**Comment by xcelr** [comment]
What was the fix?

**Comment by interbiznw** [comment]
Closed without a fix? All these issues and nobody ever tells what fixed it yet the issues are closed
