### ISSUE TITLE
toolbox and integration submodules added with incorrect commit ids

### ISSUE THREAD

**Issue by burakhoban** [rubykube/workbench#149]
As per commit 2ddc5a4beda16990022507d0305b5137fb153c0c to workbench, it updates both integration and toolbox submodules with the same commit id, which is invalid.

The toolbox submodule uses the commit id of 07bab7, which should probably be 477f96abde31aa64f9168593abf8b0060c6aa402

**Comment by shal** [comment]
Closed via #150.
