### ISSUE TITLE
What exactly is ngx-cryptobase?

### ISSUE THREAD

**Issue by javier-tarazaga** [rubykube/workbench#16]
Hi guys, 

Trying to setup the project locally but I am currently missing ngx-cryptobase. What exactly is this and where can I find the project to clone it? 

Thanks!

**Comment by CombatCode** [comment]
cherry-pick this commit https://github.com/rubykube/peatio-workbench/commit/ebf0e6e60014d4ad16c33159c91d7c062398961d to go forward with your configuration, but honestly I still don't know what is ngx-cryptobase so maybe some contributor will reply there

**Comment by wirelessjeano** [comment]
I found this: https://www.npmjs.com/package/ngx-cryptobase

**Comment by gungorkocak** [comment]
@wirelessjeano I have tried to put that npm module to necessary path, build started but failed when it seeks for Dockerfile. Message is like that:

```bash
ERROR: Cannot locate specified Dockerfile: Dockerfile
make: *** [build] Error 1
```

**Comment by wirelessjeano** [comment]
I havn't attempted to get it working. I imagine @calj or @mod will will update the workbench when they are ready.

**Comment by gungorkocak** [comment]
I had with @CombatCode 's cherrypick advice. Worked like a charm including couple of omniauth changes. Now I am trying to get on track with btc integration.
