### ISSUE TITLE
workbench database currencies:seed  issue

### ISSUE THREAD

**Issue by AnthonyRex** [rubykube/workbench#167]
I am almost done but the final stage got this issue in db seed. any idea , i don't want mess up what i did

/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
Makefile:57: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1

**Comment by CHONGErYuan** [comment]
I have a same problem. Anyone know the root cause and solution to solve it?

**Comment by AnthonyRex** [comment]
the actual issue is this 

l,\"erc20_contract_address\":null}', 'usd', '$', 'fiat', 1000.0, '2018-09-09 07:42:30', '2018-09-09 07:42:30')
  Member Load (2.8ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
  Currency Exists (1.0ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1
   (8.4ms)  ROLLBACK
rake aborted!
ActiveRecord::UnknownAttributeError: **unknown attribute 'blockchain_key'** for Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'

anyone manage to solve this?
I changed to a new image and from scratch but still the same issue

**Comment by knkrth** [comment]
I also has the same problem.

```
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
Makefile:57: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1
```

Any fix?

**Comment by shal** [comment]
This is not confirmed.

**Comment by shal** [comment]
Duplicate #144.
