### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/app/config/currencies.yml

### ISSUE THREAD

**Issue by tigwyk** [rubykube/workbench#17]
Hi guys,

I'm getting a couple different errors depending on whether I try to "Make prepare" with the master or devel branches of peatio.

Master branch:
"make build" completes without issues and seems to set up a lot of the docker images and such. Then I run "make prepare" and it comes back with the currencies.yml file being missing.

Devel branch:
"make build" completes without errors. "make prepare" complains about missing yarn assets and fails.

Previously I'd gotten peatio running via setting up docker myself (not using docker-compose, but individually setting up docker containers for redis, rabbitmq, postgres, etc). I was hoping this method would be a little faster for playing around with development.

**Comment by bitcoinli** [comment]
hi,

run command make setup-apps

![image](https://user-images.githubusercontent.com/29343319/36377665-f8ba3e86-1588-11e8-8c0c-487432c19ef8.png)

**Comment by tigwyk** [comment]
That gets me farther, but now when running setup-apps I get another error related to missing yarn components.
