### ISSUE TITLE
MAKE TEST "visit" command cant deploy

### ISSUE THREAD

**Issue by anhbaysgalan1** [rubykube/workbench#179]
/usr/src/app/support/index.js

The error was:

SyntaxError: /usr/src/app/support/commands.js: Unexpected token (25:69)

  23 | //
  24 | // -- This is will overwrite an existing command --
> 25 |  Cypress.Commands.overwrite("visit", (originalFn, url, options) => { ... })
     |                                                                      ^
  26 | 
  27 |  Cypress.Commands.add('login', () => {
  28 |      cy.request ({ while parsing file: /usr/src/app/support/commands.js

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌────────────────────────────────────┐
  │ Tests:        0                    │
  │ Passing:      0                    │
  │ Failing:      1                    │
  │ Pending:      0                    │
  │ Skipped:      0                    │
  │ Screenshots:  0                    │
  │ Video:        true                 │
  │ Duration:     0 seconds            │
  │ Spec Ran:     barong_login.spec.js │
  └────────────────────────────────────┘

  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /usr/src/app/videos/barong_login.spec.js.mp4 (1 second)

====================================================================================================

  (Run Finished)

      Spec                                                Tests  Passing  Failing  Pending  Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖ barong_login.spec.js                        0ms        -        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)                          0ms        -        -        1        -        -  

I taking this error and i configured my own domain.

**Comment by shal** [comment]
Hi @anhbaysgalan1,

Did you change/remove something from `compose/tests.yaml`?
Looks like file with integration tests did not mount.

**Comment by anhbaysgalan1** [comment]
this error is done
