### ISSUE TITLE
Some peatio daemons are missing

### ISSUE THREAD

**Issue by ysv** [rubykube/workbench#186]
https://github.com/rubykube/peatio/blob/master/docs/daemons.md
k-daemon is missing need to double check other.

List of daemons to add:
- [x] `k`
- [ ] `payment_transaction`
- [ ] other

**Comment by shal** [comment]
K daemon was added in #189.

**Comment by shal** [comment]
@mnaichuk Good job with `k` daemon, but unfortunately you didn't finish the task.

I looked thought the list and here is one more daemon, that we don't have in workbench - **payment_transaction**.

Please, take a look and double check each daemon from the list in two places:

Here:
https://github.com/rubykube/workbench/blob/1a837fd57bae833806298c00ae9cfe96815a6258/Makefile#L35-L49

Here:
https://github.com/rubykube/workbench/blob/1a837fd57bae833806298c00ae9cfe96815a6258/compose/daemons.yaml#L21-L80

**Comment by shal** [comment]
According to @mnaichuk - issue is fixed. Other daemons are unneeded.
