### ISSUE TITLE
run site public ip

### ISSUE THREAD

**Issue by GerardoTaboada** [rubykube/workbench#190]
Hi, where are you given permissions to run the site from ip public? that only works for me as localhost only, I have already edited the hosts file. Thank you very much!

make run....

http://xx.xxx.xxx/api.wb.local
404 page not found

**Comment by shal** [comment]
Hello @GerardoTaboada,

Sorry, I didn't get the question/bug report. Seems like you doing something wrong.

Workbench has proxy - **traefik**, that works great with docker compose.

In default version it runs on `*.wb.local`, but on `localhost`. 

You **have ability** to change `*.wb.local` to your domain. 
In this case you can expose machine with workbench to the network.
- Point exact IP.
- Cleaning up `/etc/hosts/` file.

For information please read  [article](https://github.com/rubykube/workbench/wiki/How-to-make-custom-DNS%3F).

**Comment by DommeCoin** [comment]
Having the same problem, changed the hostfile to api.mydomain.com and still doessent connect i get a time out error when i https://mydomain.com

**Comment by shal** [comment]
Hi @GerardoTaboada,

I think you did something wrong with firewall or DNS record, so it is not related to workbench.

Please **double check**:
- Public IP that pointed to DNS record.
- 80 and 443 of machine are accessible from network.

**Comment by shal** [comment]
Nice! 👍

**Comment by knkrth** [comment]
Hi, After `make build` & `make run` is it possible to access the exchange without the domain name by using only the AWS/DigitalOcean internal ip address? (ie. https://auth.192.168.1.1/)

**Comment by shal** [comment]
Hello @GerardoTaboada, it is not possible.

**Comment by AbdaalRuhaani** [comment]
hy guys i am facing same issue but different formats of urls not working...
