### ISSUE TITLE
Mysql2::Error: Unknown MySQL server host 'db' (-2)

### ISSUE THREAD

**Issue by 3ryuan** [rubykube/workbench#192]
I getting this error

#<Mysql2::Error: Unknown MySQL server host 'db' (-2)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "collation"=>"utf8_general_ci", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>"changeme", "database"=>"peatio_development"}, {:charset=>"utf8", :collation=>"utf8_general_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
Mysql2::Error: Unknown MySQL server host 'db' (-2)
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:941:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Makefile:61: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1

Anyone can help?

**Comment by knkrth** [comment]
I also have this error. Any solution?

**Comment by 3ryuan** [comment]
> I also have this error. Any solution?

What's cloud service you used? Last time, I used digital ocean and this error always come out.
Please try another cloud service like GCP and AWS.

**Comment by sravanikambhampati** [comment]
I am also facing the same issue. I am using aws cloud and for CI bamboo


rake aborted!
--
28-Nov-2018 03:09:27 | Mysql2::Error: Unknown MySQL server host 'db' (0)


rake aborted!
--
28-Nov-2018 03:09:27 | Mysql2::Error: Unknown MySQL server host 'db' (0)
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
28-Nov-2018 03:09:27 | /usr/local/rvm/gems/ruby-2.3.7/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'

**Comment by TTcoinDeveloper** [comment]
Ever got this solved??

**Comment by knkrth** [comment]
Did you try different servers?

**Comment by TTcoinDeveloper** [comment]
Yess everything

**Comment by knkrth** [comment]
Rise this issue on [Rubykube Discourse Forum](https://discuss.rubykube.io/) or [Telegram](https://t.me/peatio)

**Comment by ysoup** [comment]
I also have this error. Any solution?
