### ISSUE TITLE
cannot pull vault

### ISSUE THREAD

**Issue by Thedabest** [rubykube/workbench#195]
cannot pull vault
![image](https://user-images.githubusercontent.com/40519768/45955273-9fb66600-c039-11e8-9573-247b291bd45b.png)

**Comment by shal** [comment]
Hello @Thedabest,

For me it worked.

<img width="1280" alt="screen shot 2018-09-25 at 13 50 32" src="https://user-images.githubusercontent.com/15674738/46010079-17cc6c80-c0ca-11e8-90ff-dfaced00e1d2.png">
