### ISSUE TITLE
Cant open peatio

### ISSUE THREAD

**Issue by lordvalium** [rubykube/workbench#203]
Hi, 
i followed this issue: 
https://github.com/rubykube/workbench/issues/190 and this wiki entry:
https://github.com/rubykube/workbench/wiki/Google-Cloud-Platform-Installation

executed the script and replaced it with _domain.de_
After that i went to my domain provider and put the external IPV4 to the target of the domain redirection. 

But i cant open wb.domain.de nor domain.de neiter under the IPV4 adress. 

/etc/hosts is not changed, and HTTP and HTTPS traffic is allowed - 80 and 443 is open though?!

**Comment by lordvalium** [comment]
Hello @shal 
thanks for your reply. 
Yes i did the **A record** in GCP. 
And i changed also the /etc/hosts to that IP. Right?

**Comment by shal** [comment]
@lordvalium no, clean up `/etc/hosts`.

**Comment by lordvalium** [comment]
Hi @shal, i have cleaned-up `/etc/hosts` but still can not open api.domain.de nor api.wb.domain.de

what could it be, do i have to run `make run` again?
thank you

**Comment by shal** [comment]
@lordvalium, try to check it using `httpie` or `curl`.
Shot output above.

**Comment by lordvalium** [comment]
Hi @shal  - thx, i did not know httpie. 
`
peatio:~$ http api.wb.pk6.de

http: error: ConnectionError: HTTPConnectionPool(host='api.wb.pk6.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0abe37d110>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing GET request to URL: http://api.wb.pk6.de/

`
and
`peatio:~$ http api.pk6.de

http: error: ConnectionError: HTTPConnectionPool(host='api.pk6.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8f63a990d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing GET request to URL: http://api.pk6.de/
`
and 
`peatio:~$ http localhost

http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f10c09220d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing GET request to URL: http://localhost/
`
I dont get it whats the problem in my system :(

**Comment by lordvalium** [comment]
I changed the config files "new_domain" and now:

`workbench@peatio2:~/workbench$ http pk6.de
HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Wed, 17 Oct 2018 19:16:51 GMT
X-Content-Type-Options: nosniff

404 page not found

workbench@peatio2:~/workbench$ http auth.wb.pk6.de
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-Length: 104
Content-Type: text/html; charset=utf-8
Date: Wed, 17 Oct 2018 19:17:05 GMT
Location: http://auth.wb.pk6.de/accounts/sign_in
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 5199bc0c-aeea-41b6-acd5-c03daf076697
X-Runtime: 0.055067
X-Xss-Protection: 1; mode=block

<html><body>You are being <a href="http://auth.wb.pk6.de/accounts/sign_in">redirected</a>.</body></html>

workbench@peatio2:~/workbench$`

**Comment by shal** [comment]
Sorry, you doing something wrong, consider ask help in telegram channel :smile:
