### ISSUE TITLE
How to run MySQL commands and bitcoin-cli

### ISSUE THREAD

**Issue by Coding-Jewelry** [rubykube/workbench#204]
Dear Peatio team.

Now I am trying to setup and consider Rubykube Peatio exchange.
I have already installed Peatio running by using workbench.git.
What I want to do is to run MySQL queries and bitcoin-cli for considering Peatio's back-end, but unfortunately I am not sure how I can enter it.
I appreciate you if you let me know how to do this.

Thank you.

**Comment by shal** [comment]
Hello @Coding-Jewelry,

Access to mysql:

```sh
$> docker exec -it workbench_db_1 -- sh
```

Access to bitcoin-cli

```sh
$> docker exec -it workbench_bitcoin_1 -- sh
```

@Coding-Jewelry Consider closing issue, if this answer fit your needs.
