### ISSUE TITLE
Deposit Bitcoin but history and amount not showing and update

### ISSUE THREAD

**Issue by 3ryuan** [rubykube/workbench#206]
I deposited the bitcoin into account but history and amount not showing.
Anyone know how to solve it?

**Comment by 3ryuan** [comment]
Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
deposit_coin_address_1     |    from /opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/session.rb:302:in `sta
rt'
deposit_coin_address_1     |    from lib/daemons/amqp_daemon.rb:11:in `<main>'
deposit_coin_address_1     | W, [2018-10-12T13:55:50.727814 #1]  WARN -- #<Bunny::Session:0x5644237617c8 guest@rabbit
mq:5672, vhost=/, addresses=[rabbitmq:5672]>: Could not establish TCP connection to rabbitmq:5672: Connection refused
 - connect(2) for 172.18.0.6:5672
deposit_coin_address_1     | Link /opt/peatio/config/seed/wallets.yml -> /home/app/config/seed/wallets.yml
deposit_coin_address_1     | Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
deposit_coin_address_1     | Link /opt/peatio/config/seed/blockchains.yml -> /home/app/config/seed/blockchains.yml
deposit_coin_address_1     | Link /opt/peatio/config/seed/markets.yml -> /home/app/config/seed/markets.yml
deposit_coin_address_1     | Link /opt/peatio/config/plugins.yml -> /home/app/config/plugins.yml
deposit_coin_address_1     | Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml

I think is this error causing the problem I mentioned above.

**Comment by 3ryuan** [comment]
![image](https://user-images.githubusercontent.com/35586548/46899429-c55ebe80-cec5-11e8-9578-b99d083a101c.png)

I found this error in 'bitcoind_1' log. --> Binding RPC on address :: port 18332 failed
Any solution?

**Comment by Thedabest** [comment]
@3ryuan is this workbench 1.8?

**Comment by UfukAntep** [comment]
Have you solved the problem? I'm having a similar problem
