### ISSUE TITLE
Trading UI, withdrawal, add new market pairs not working

### ISSUE THREAD

**Issue by 3ryuan** [rubykube/workbench#207]
![image](https://user-images.githubusercontent.com/35586548/46880838-56a94300-ce7c-11e8-8067-aad249d27282.png)

Anyone can explain this to me?

**Comment by shal** [comment]
Hello,

Seems like you workbench build was not successful, or you changed code inside workbench.

**Comment by 3ryuan** [comment]
@shal 

I followed the document you provided to deploy the workbench on GCP and change nothing inside the code. No error when build and run. The first and second days still running without any problem. Third day, I try to login then this error popup suddenly.
