### ISSUE TITLE
"Creating workbench_db_1 ... error" when make run

### ISSUE THREAD

**Issue by lsls01** [rubykube/workbench#209]
➜ make run
docker-compose up -d vault db phpmyadmin redis rabbitmq mailcatcher ranger coinhub
workbench_redis_1 is up-to-date
workbench_rabbitmq_1 is up-to-date
workbench_mailcatcher_1 is up-to-date
workbench_coinhub_1 is up-to-date
Starting workbench_db_1 ... 
workbench_vault_1 is up-to-date
Starting workbench_db_1 ... error

ERROR: for workbench_db_1  Cannot start service db: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/username/workbench/config/mysql/my.cnf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/f1eb0f4bbca130a96f2b7abe77543fe8e1471fa9ce757dc20da83fa18e650e57\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/f1eb0f4bbca130a96f2b7abe77543fe8e1471fa9ce757dc20da83fa18e650e57/etc/mysql/mysql.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/username/workbench/config/mysql/my.cnf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/f1eb0f4bbca130a96f2b7abe77543fe8e1471fa9ce757dc20da83fa18e650e57\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/f1eb0f4bbca130a96f2b7abe77543fe8e1471fa9ce757dc20da83fa18e650e57/etc/mysql/mysql.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

I am using the latest code in master branch. Is there anyone know how to fix this?

**Comment by shal** [comment]
Hello @lsls01, I think you have bad internet connection, don't you?

What machine do you use to setup workbench?

**Comment by lsls01** [comment]
Hello @shal My internet is good in most cases and I don't think it's related to internet connection, because the 'make run' process in Makefile seems totally offline.

I was trying deploying workbench on a HP ZBook with Manjaro Linux. All packages are up to date.

**Comment by shal** [comment]
@lsls01 Ok, can you try one more time and provide file with full log of workbench build?
