### ISSUE TITLE
Gem::LoadError:

### ISSUE THREAD

**Issue by Gensia** [rubykube/workbench#211]
$> docker-compose run --rm peatio bash -c "./bin/link_config && rake db:create db:migrate db:seed"
Returns the following error:
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 12.3.1. Prepending 'bundle exec' to your command may solve this.
/home/app/config/boot.rb:6:in '<top (required)>'
/home/app/config/application.rb:4:in '<top (required)>'
/home/app/Rakefile:8:in '<top (required)>'

Prepending 'bundle exec' doesnt fix.
Also tried:
bundle update
sudo bundle update rake
sudo gem install rake -v 12.3.1

Also deleted gemlock files and tried again same error

**Comment by shal** [comment]
After [this patch](https://github.com/rubykube/peatio/commit/649c88e59e1d79830c1e23408b98ae40ce5d79f9) , it is required to use bundler in peatio docker image.

```
$> docker-compose run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate db:seed"
```

**Comment by Gensia** [comment]
Thanks for that I had the bundle exec in wrong place.
