### ISSUE TITLE
Add new coin in workbench

### ISSUE THREAD

**Issue by franklee1** [rubykube/workbench#215]
How can we add new coin in workbench?

**Comment by shal** [comment]
Hi @franklee1,

In public version of workbench there are only two coins:

- **BTC**
- **ETH**

You can fork it and add any other coin, supported by rubykube/peatio.

**Comment by franklee1** [comment]
Thanks for replying, I was trying to add Dogecoin and I get following error

ActiveRecord::RecordInvalid: Validation failed: Gateway is not included in the list

is there a way to add gateway?

**Comment by franklee1** [comment]
I've already made changes in the blockchain services and lib folder.

**Comment by shal** [comment]
@franklee1 No, peatio doesn't support this coin.

**Comment by franklee1** [comment]
is there a paid service that you guys offer to put unsupported coins? I contacted Rubykube team from the website but got no response.

**Comment by champmine** [comment]
@shal 
can you be more specific about this?

To add new coin, you need to add it info following configuration

    Blockchain
    Wallets
    Currency

Also you need rpc node of this currency.

**Comment by champmine** [comment]
well, in the 1-8-stable branch those files do not exist
the current branch is not working, db migration fails
Any ETA for a working current master?

**Comment by shal** [comment]
@franklee1 Current master works :)

**Comment by shal** [comment]
You can see CI check-mark, it means everything should work correctly.
