### ISSUE TITLE
docker-composer - `/home/app` is not writable.

### ISSUE THREAD

**Issue by myujang** [rubykube/workbench#22]
I come across some error while running 'make setup-apps'
`/home/app` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.

After some digging and testing. i change the docker-composer on volumes to increment number then all make no issues.    
volumes:
      - ./barong:/home/app4

**Comment by sosospicy** [comment]
Problem solved by reboot system .   don't know the reazon...  : s

**Comment by dkkoval** [comment]
The reason is that when we mount a local directory to the container, it keeps you local ownership. In short, it's read-only for the `app` user inside the container (unless your host user has `uid: 1000`)

Simple workaround:
```
sudo chown 1000 -R barong/ peatio/
make setup-apps
sudo chown $USER -R barong/ peatio/
```

Closing, feel free to reopen if that didn't help.
