### ISSUE TITLE
Eror on make run 

### ISSUE THREAD

**Issue by cryptonana** [rubykube/workbench#227]
hello dear when i make build its show docker file not found after i talk telegram you send me this command 

docker-compose build peatio     \
                 barong     \
                 trading_ui

all good but when i run 

make run its show me again error
workbench@workbench:~/workbench$ make run
docker-compose up -d vault db phpmyadmin redis rabbitmq mailcatcher ranger coinhub
ERROR: Couldn't find env file: /home/workbench/workbench/config/peatio.env
Makefile:55: recipe for target 'dependencies' failed
make: *** [dependencies] Error 1

please how can i resolve this issu

and one more problem

when clone

git clone --recursive https://www.github.com/rubykube/workbench.git && cd workbench
Submodule path 'app/barong': checked out '4a1137e050a9e7d9bd1e578dd2dd9f798ce5559a'
Submodule path 'app/peatio': checked out '551114f48f3a241cd6782d54513c24fc5e6b4564'
Submodule path 'app/trading-ui': checked out 'd8c3dba7143f15244ecbf3210ae26e9d0cb8aae6'
error: no such remote ref 4c0e6cc8fb1ac57c330e2e184856a667e7701f68
Fetched in submodule path 'test/integration', but it did not contain 4c0e6cc8fb1ac57c330e2e184856a667e7701f68. Direct fetching of that commit failed.

its show this on integration

**Comment by openbooknoobdeveloper** [comment]
@cryptonana did u solve your issue? how? thank you
