### ISSUE TITLE
ActionController::InvalidAuthenticityToken in SessionsController#confirm

### ISSUE THREAD

**Issue by cryptonana** [rubykube/workbench#228]
every thing ok when i try to login its show me this error

![untitled](https://user-images.githubusercontent.com/40866572/48379140-f3335080-e687-11e8-8f99-e914f306e547.png)

please tell me how to resolve this issue

**Comment by shal** [comment]
Hi @cryptonana, 

Try to cleanup your cookies.

**Comment by cryptonana** [comment]
@shal not resolve please help

**Comment by AkashiHidaka** [comment]
After code update show this error.
It isn't work of code update work.
![routing](https://user-images.githubusercontent.com/44053447/48852001-64d97000-ede7-11e8-8892-59b623633770.png)
![image](https://user-images.githubusercontent.com/44053447/48852028-6c991480-ede7-11e8-95af-6c41db70cf11.png)
How to solve this error?

**Comment by ndacoin** [comment]
I am getting same error when I tried to login 
![screen shot 2018-11-23 at 3 59 07 pm](https://user-images.githubusercontent.com/38830823/48938972-cbba6e80-ef38-11e8-9e5a-129267244e34.png)


Please help

**Comment by champmine** [comment]
C'mon, closing the issue, why? It is not resolved at all!

**Comment by saydulk** [comment]
I am using Workbench 2. Getting same problem on Debian 9 LInux. @shal Ali is their any solution?  

![Screenshot from 2019-07-02 12-48-54](https://user-images.githubusercontent.com/1058663/60490150-c8a21080-9cc7-11e9-92e9-a65b0b690605.png)

**Comment by shal** [comment]
@saydulk Workbench is deprecated.

**Comment by saydulk** [comment]
@shal so what i will use for deploy Peatio exchange server?

**Comment by shal** [comment]
See https://github.com/rubykube/microkube

**Comment by saydulk** [comment]
@shal Trades coming soon! I see a close issue here https://github.com/rubykube/microkube/issues/92

it also asking me to installing Peatio 1.9 with the workbench project. I am confuse wheather i will use workbench or microkube ? 

![Screenshot from 2019-07-07 17-07-45](https://user-images.githubusercontent.com/1058663/60767607-0e057a00-a0dc-11e9-8952-8868b61ea38d.png)

**Comment by guru260** [comment]
@saydulk @cryptonana Did you find solution for this issue?

**Comment by saydulk** [comment]
@guru260 no not yet

**Comment by guru260** [comment]
@saydulk I have fixed this issue. I have changed manually my domain name api.wb.local to api.xyz.abc and auth.wb.local to auth.xyz.abc. But I forgot to change ROOT_DOMAIN in barong.env.erb. This ROOT_DOMAIN name will be used in development.rb and production.rb file for session_store. We can either change ROOT_DOMAIN or change root domain directly in development.rb/production.rb. Let me know If you have same problem like this.

**Comment by saydulk** [comment]
@guru260 thanks it work for me too :)

**Comment by saydulk** [comment]
@guru260 how i can setup xyz.abc or domain.com not api.xyz.abc or api.domain.com?

**Comment by guru260** [comment]
suppose your domain name is api.xyz.com for peatio, auth.xyz.com for barong, then you have to set xyz.com in session_store.rb file as domain name.

**Comment by saydulk** [comment]
what is the location of session_store.rb file?

**Comment by guru260** [comment]
config/initializers/session_store.rb
