### ISSUE TITLE
Fetched in submodule path 'test/integration', but it did not contain 4c0e6cc8fb1ac57c330e2e184856a667e7701f68. Direct fetching of that commit failed.

### ISSUE THREAD

**Issue by ndacoin** [rubykube/workbench#229]
Hello

I am following this link (https://github.com/rubykube/workbench/wiki/DigitalOcean-Installation) to install workbench, but while Download workbench (git clone --recursive https://www.github.com/rubykube/workbench.git && cd workbench)
I am getting this error 

Cloning into '/home/workbench/workbench/test/toolbox'...
remote: Enumerating objects: 82, done.        
remote: Total 82 (delta 0), reused 0 (delta 0), pack-reused 82        
Submodule path 'app/barong': checked out '4a1137e050a9e7d9bd1e578dd2dd9f798ce5559a'
Submodule path 'app/peatio': checked out '551114f48f3a241cd6782d54513c24fc5e6b4564'
Submodule path 'app/trading-ui': checked out 'd8c3dba7143f15244ecbf3210ae26e9d0cb8aae6'
error: no such remote ref 4c0e6cc8fb1ac57c330e2e184856a667e7701f68
Fetched in submodule path 'test/integration', but it did not contain 4c0e6cc8fb1ac57c330e2e184856a667e7701f68. Direct fetching of that commit failed.

Please let me know how can I solve this problem.
Thanks in advance

**Comment by ndacoin** [comment]
can anyone help

**Comment by dovidgef** [comment]
I am having this issue as well. Anyone know how to fix it?

**Comment by AkashiHidaka** [comment]
I having same issue and by it in "docker-compose build integration"  module no working.
How to solve this problem?

**Comment by openbooknoobdeveloper** [comment]
I am having the same error but with test/toolbox

```
Submodule path 'test/toolbox': checked out '477f96abde31aa64f9168593abf8b0060c6aa402'
Unable to checkout '4c0e6cc8fb1ac57c330e2e184856a667e7701f68' in submodule path 'test/integration'
```

**Comment by Thedabest** [comment]
rm -rf test/integration
git clone https://github.com/rubykube/integration test/integration

**Comment by shal** [comment]
Fixed.
