### ISSUE TITLE
Unable to checkout '4c0e6cc8fb1ac57c330e2e184856a667e7701f68' in submodule path 'test/integration'

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [rubykube/workbench#230]
I am getting this error when I cloning the project:
**git clone --recursive https://github.com/rubykube/workbench.git**

```
fatal: reference is not a tree: 4c0e6cc8fb1ac57c330e2e184856a667e7701f68
Cloning into 'test/toolbox'...
remote: Enumerating objects: 82, done.
remote: Total 82 (delta 0), reused 0 (delta 0), pack-reused 82
Unpacking objects: 100% (82/82), done.
Checking connectivity... done.
Submodule path 'test/toolbox': checked out '477f96abde31aa64f9168593abf8b0060c6aa402'
Unable to checkout '4c0e6cc8fb1ac57c330e2e184856a667e7701f68' in submodule path 'test/integration'

```

**Comment by Vadim-002** [comment]
same here

**Comment by AkashiHidaka** [comment]
By it all elements build and run.
After "make run" command no working anything.
![image](https://user-images.githubusercontent.com/44053447/48730402-3471c480-ec75-11e8-8cdc-1ee3c4fcd36b.png)
In this image show it run , but no show anything of the result.

**Comment by Vadim-002** [comment]
Thank you for your reply, a little later I got it to work. I believe ‘make update’ fixed the issue

**Comment by AkashiHidaka** [comment]
No , it isn't fixed and no working.

**Comment by openbooknoobdeveloper** [comment]
fixed.
