### ISSUE TITLE
barong Your account is locked 

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [rubykube/workbench#232]
I tried sign in  in: http://auth.wb.local/
with
Email: admin@barong.io
Password: Qwerty123

and said the password was wrong, I tried multiple times and now the account is locked.

how can I access the system?

thank you.

**Comment by Thedabest** [comment]
https://github.com/rubykube/workbench/blob/master/config/barong/seeds.yml#L11
password barong admin now changed to Chah5YohWm

**Comment by Thedabest** [comment]
sloved

**Comment by AkashiHidaka** [comment]
Hello
The code correctly compile and why it isn't work in my domain?
What is the reason of it?
It show "404 page not found" in first page and other sub domains no working.
I hosted it in Digital Ocean server.
