### ISSUE TITLE
EUR, USD Deposit not working.

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [rubykube/workbench#233]
how to reproduce: 

access:
http://api.wb.local/admin/deposits/eur/new

click + new deposit.

fill up Amount and SN.

click accept.

I get a message: 
Member can't be blank 

why? where is that field?

**Comment by pkucherenk0** [comment]
@openbooknoobdeveloper Good day to you.
Have you copied the SN code from the member list of account you want to deposit to?
![selection_737](https://user-images.githubusercontent.com/38254545/48760606-22ad1300-ecaf-11e8-8756-dbb244db5d65.png)
This error is occurred went the SN filled with code that is not exist in member list.

**Comment by openbooknoobdeveloper** [comment]
@pkucherenk0  thanks man, it is working now.
