### ISSUE TITLE
Build Using Docker fails because of Yarn and dropify

### ISSUE THREAD

**Issue by applyThoughts** [rubykube/workbench#24]
Step 18/21 : RUN bundle exec rake tmp:create yarn:install assets:precompile
 ---> Running in 445e6d932c62
mkdir -p tmp/cache
mkdir -p tmp/sockets
mkdir -p tmp/pids
mkdir -p tmp/cache/assets
/usr/bin/env: 'ruby\r': No such file or directory
rake aborted!
Sprockets::FileNotFound: couldn't find file 'dropify/src/js/dropify' with type 'application/javascript'
Checked in these paths:
  /home/app/app/assets/config
  /home/app/app/assets/images
  /home/app/app/assets/javascripts
  /home/app/app/assets/stylesheets
  /home/app/vendor/assets/fonts
  /home/app/vendor/assets/javascripts
  /home/app/vendor/assets/stylesheets
  /opt/vendor/bundle/ruby/2.5.0/gems/bootstrap-datepicker-rails-1.7.1.1/vendor/assets/javascripts
  /opt/vendor/bundle/ruby/2.5.0/gems/bootstrap-datepicker-rails-1.7.1.1/vendor/assets/stylesheets
  /opt/vendor/bundle/ruby/2.5.0/gems/doorkeeper-4.2.6/app/assets/stylesheets
  /opt/vendor/bundle/ruby/2.5.0/gems/doorkeeper-4.2.6/vendor/assets/stylesheets
  /opt/vendor/bundle/ruby/2.5.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /opt/vendor/bundle/ruby/2.5.0/gems/actioncable-5.1.4/lib/assets/compiled
  /opt/vendor/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/assets/compiled
  /home/app/vendor/assets/fonts
  /home/app/node_modules
  /opt/vendor/bundle/ruby/2.5.0/gems/popper_js-1.12.9/assets/javascripts
  /opt/vendor/bundle/ruby/2.5.0/gems/bootstrap-4.0.0/assets/stylesheets
  /opt/vendor/bundle/ruby/2.5.0/gems/bootstrap-4.0.0/assets/javascripts
/home/app/app/assets/javascripts/web.js:6
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in `resolve'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
ERROR: Service 'barong' failed to build: The command '/bin/sh -c bundle exec rake tmp:create yarn:install assets:precompile' returned a non-zero code: 1

**Comment by devsur** [comment]
@applyThoughts did you manage to fix this? i am getting a similar error

**Comment by dkkoval** [comment]
It should be fixed by [peatio#675](https://github.com/rubykube/peatio/pull/675).

Closing, feel free to reopen if needed.
