### ISSUE TITLE
error on macOs when  make build

### ISSUE THREAD

**Issue by jieek** [rubykube/workbench#240]
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'barong' failed to build: The command '/bin/sh -c groupadd -r app --gid=1000  && useradd -r -m -g app -d /home/app --uid=1000 app  && curl -sL https://deb.nodesource.com/setup_8.x | bash -  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list  && apt-get update  && apt-get install -y imagemagick nodejs yarn' returned a non-zero code: 100
make: *** [build] Error 1

**Comment by shal** [comment]
Closed because of inactivity of more that 14 days.
