### ISSUE TITLE
Getting errro on installation can't read config/peatio.env, can't read config/barong.env & can't read config/toolbox.yaml

### ISSUE THREAD

**Issue by ndacoin** [rubykube/workbench#241]
Hello,

I am following https://github.com/rubykube/workbench/wiki/DigitalOcean-Installation,

First I got error : (Fetched in submodule path 'test/integration', but it did not contain 4c0e6cc8fb1ac57c330e2e184856a667e7701f68. Direct fetching of that commit failed. #229 )for whic I got answer.

And now instep 
Replace domain
Set $new_domain variable equal to your domain and run bash script:
After running the bash script I am getting this
workbench@bitrish:~/workbench$ ./test.sh 
sed: can't read config/peatio.env: No such file or directory
sed: can't read config/barong.env: No such file or directory
sed: can't read config/toolbox.yaml: No such file or directory

Please let know what to do.

Regards

**Comment by Tunnulincadmin** [comment]
I have to admit I am always getting this error, the files in there have the following extension .env.erb ... soo idk if I should change my script to include env.erb then cp them into .env files  ... should this work

**Comment by shal** [comment]
Closed via #265.

**Comment by mur-wtag** [comment]
so what is the solution here?
