### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by aminaqi** [rubykube/workbench#244]
get this error while i try make build:

 Service 'barong' failed to build: The command '/bin/sh -c mkdir -p /opt/v        endor/bundle && chown -R app:app /opt/vendor  && su app -s /bin/bash -c "bundle         install --path /opt/vendor/bundle"' returned a non-zero code: 5
Makefile:22: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by TTcoinDeveloper** [comment]
https://github.com/rubykube/workbench/issues/247 
this issue should be merged

**Comment by shal** [comment]
@aminaqi Consider switching to latest master of workbench, this issue should be fixed there.

**Comment by jesangi** [comment]
same ERROR
I use latest master of workbench

Fetching discard 1.0.0
Installing discard 1.0.0
Fetching docile 1.3.1
Installing docile 1.3.1
Fetching unf_ext 0.0.7.5
Installing unf_ext 0.0.7.5 with native extensions
ERROR: Service 'barong' failed to build: The command '/bin/sh -c mkdir -p /opt/vendor/bundle && chown -R app:app /opt/vendor  && su app -s /bin/bash -c "bundle install --path /opt/vendor/bundle"' returned a non-zero code: 137
Makefile:22: 'build'
