### ISSUE TITLE
Issue with ERROR: Service 'barong' failed to build

### ISSUE THREAD

**Issue by ramror3** [rubykube/workbench#247]
Hi to all,
    While i setup the workbench in my local i'm getting this type of issue. Could you please help me with this issue.
Thanks.
![screenshot from 2018-11-28 12-42-46](https://user-images.githubusercontent.com/28476360/49135134-dcd5f780-f30b-11e8-8977-eb846ba6edd7.png)

**Comment by TTcoinDeveloper** [comment]
build 
$> rbenv install -v 2.5.1
$> rbenv global 2.5.1

as non root user if u dont everything else will eventually fail later on

**Comment by ramror3** [comment]
@TTcoinDeveloper  Thank you for giving info.
