### ISSUE TITLE
RPC password is not set.

### ISSUE THREAD

**Issue by ramror3** [rubykube/workbench#252]
Hi to all,
I'm facing issue with RPC user and Password. How to set RPC credentials
![bit](https://user-images.githubusercontent.com/28476360/49497945-99413780-f88f-11e8-8178-241c52fb7148.png)
 please help me with this issue. I'm getting this type of error. Please refer the below screenshot.
Thanks.

**Comment by Thedabest** [comment]
pls send this issuse to https://github.com/bitcoin/bitcoin

**Comment by ramror3** [comment]
Okay.
Thanks.
