### ISSUE TITLE
traefik - Unable to obtain ACME certificate for domains

### ISSUE THREAD

**Issue by UfukAntep** [rubykube/workbench#254]
Hello,

I look at the traefik log, and I see a error. How can I solve this? 

level=error msg="Unable to obtain ACME certificate for domains \"btc.wb.local\" detected thanks to rule \"Host: btc.wb.local\" : unable to generate a certificate for the domains [btc.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:19Z" level=error msg="Unable to obtain ACME certificate for domains \"api.wb.local\" detected thanks to rule \"Host: api.wb.local; PathPrefix:/trading, /trading-ui-assets\" : unable to generate a certificate for the domains [api.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:19Z" level=error msg="Unable to obtain ACME certificate for domains \"pma.wb.local\" detected thanks to rule \"Host: pma.wb.local\" : unable to generate a certificate for the domains [pma.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:20Z" level=error msg="Unable to obtain ACME certificate for domains \"mail.wb.local\" detected thanks to rule \"Host: mail.wb.local\" : unable to generate a certificate for the domains [mail.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:21Z" level=error msg="Unable to obtain ACME certificate for domains \"monitor.wb.local\" detected thanks to rule \"Host: monitor.wb.local\" : unable to generate a certificate for the domains [monitor.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:21Z" level=error msg="Unable to obtain ACME certificate for domains \"ws.ranger.wb.local\" detected thanks to rule \"Host: ws.ranger.wb.local\" : unable to generate a certificate for the domains [ws.ranger.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:21Z" level=error msg="Unable to obtain ACME certificate for domains \"rabbitmq.wb.local\" detected thanks to rule \"Host: rabbitmq.wb.local\" : unable to generate a certificate for the domains [rabbitmq.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:21Z" level=error msg="Unable to obtain ACME certificate for domains \"eth.wb.local\" detected thanks to rule \"Host: eth.wb.local\" : unable to generate a certificate for the domains [eth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:22Z" level=error msg="Unable to obtain ACME certificate for domains \"auth.wb.local\" detected thanks to rule \"Host: auth.wb.local\" : unable to generate a certificate for the domains [auth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:38Z" level=info msg="Server configuration reloaded on :443"
time="2018-12-06T08:46:38Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-06T08:46:38Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"monitor.wb.local\" detected thanks to rule \"Host: monitor.wb.local\" : unable to generate a certificate for the domains [monitor.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"eth.wb.local\" detected thanks to rule \"Host: eth.wb.local\" : unable to generate a certificate for the domains [eth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"auth.wb.local\" detected thanks to rule \"Host: auth.wb.local\" : unable to generate a certificate for the domains [auth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"rabbitmq.wb.local\" detected thanks to rule \"Host: rabbitmq.wb.local\" : unable to generate a certificate for the domains [rabbitmq.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"pma.wb.local\" detected thanks to rule \"Host: pma.wb.local\" : unable to generate a certificate for the domains [pma.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"ws.ranger.wb.local\" detected thanks to rule \"Host: ws.ranger.wb.local\" : unable to generate a certificate for the domains [ws.ranger.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"mail.wb.local\" detected thanks to rule \"Host: mail.wb.local\" : unable to generate a certificate for the domains [mail.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"btc.wb.local\" detected thanks to rule \"Host: btc.wb.local\" : unable to generate a certificate for the domains [btc.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:40Z" level=info msg="Server configuration reloaded on :443"
time="2018-12-06T08:46:40Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-06T08:46:40Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"api.wb.local\" detected thanks to rule \"Host: api.wb.local\" : unable to generate a certificate for the domains [api.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"btc.wb.local\" detected thanks to rule \"Host: btc.wb.local\" : unable to generate a certificate for the domains [btc.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"monitor.wb.local\" detected thanks to rule \"Host: monitor.wb.local\" : unable to generate a certificate for the domains [monitor.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"mail.wb.local\" detected thanks to rule \"Host: mail.wb.local\" : unable to generate a certificate for the domains [mail.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"eth.wb.local\" detected thanks to rule \"Host: eth.wb.local\" : unable to generate a certificate for the domains [eth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"auth.wb.local\" detected thanks to rule \"Host: auth.wb.local\" : unable to generate a certificate for the domains [auth.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"ws.ranger.wb.local\" detected thanks to rule \"Host: ws.ranger.wb.local\" : unable to generate a certificate for the domains [ws.ranger.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"pma.wb.local\" detected thanks to rule \"Host: pma.wb.local\" : unable to generate a certificate for the domains [pma.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:46:42Z" level=error msg="Unable to obtain ACME certificate for domains \"rabbitmq.wb.local\" detected thanks to rule \"Host: rabbitmq.wb.local\" : unable to generate a certificate for the domains [rabbitmq.wb.local]: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix"
time="2018-12-06T08:47:15Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:47:15Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:47:16Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:47:16Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:48:17Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:48:18Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:48:19Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:48:19Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:49:21Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:49:22Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:49:24Z" level=info msg="Skipping same configuration for provider docker"
time="2018-12-06T08:49:25Z" level=info msg="Skipping same configuration for provider docker"

**Comment by TTcoinDeveloper** [comment]
try updating docker-compose version

**Comment by UfukAntep** [comment]
Hi thanks

I solved the problem. This error is happening because I use a failed commit. Solved using the last successful build.
