### ISSUE TITLE
what does it mean ?: docker-compose.yaml:BARONG_OAUTH2_REDIRECT_URL=http://localhost:4200/callback

### ISSUE THREAD

**Issue by sosospicy** [rubykube/workbench#26]
Actually, there's no service listening 4200
What does this configuration mean? What's it supposed to be?

**Comment by arausseo** [comment]
I noticed this too...  I changed to http://peatio:8000/auth/barong/callback  to receive the callbacks from barong...

**Comment by sosospicy** [comment]
@arausseo Thanks for your answer.  I did the same change, and left it behind.  : s
And I found a problem about running peatio with barong : When I click 'Exit' to logout, it seems that  the site doesn't destroy my session. When I click 'sign in with barong', the site goes to '/settings' page directly.
This problem doesn't exist when running peatio with oauth or google.
I'm not sure if I made some configuration mistake or it's a bug.

**Comment by antonror** [comment]
That was my issue too #33 
Closing this one
