### ISSUE TITLE
How can I produce the test bitcoin?

### ISSUE THREAD

**Issue by UfukAntep** [rubykube/workbench#264]
I want to do a trade test between my 2 accounts. But I don't have bitcoin and money. How can I produce the test bitcoin?

**Comment by shal** [comment]
Hi @UfukAntep,

You need to start from scratch, first step should be:

```
$> make bitcoin
```

Then run workbench as usual:

```
$> make start
```

**BUT** you will need to sync all bicoind testnet blockchain locally.

**Comment by shal** [comment]
Follow this steps:

Stop all running containers

```
$> docker rm -f $(docker ps -aq)
```

Drop database

```
$> docker volume prune -f
```

Start Bitcoin Node

```
$> make bitcoind
```

Run workbench

```
$> make start
```

**Comment by shal** [comment]
@UfukAntep if it will not work you, we can't help anymore. Good Luck!
