### ISSUE TITLE
make run fails at peatio db migration

### ISSUE THREAD

**Issue by champmine** [rubykube/workbench#266]
ActiveRecord::SchemaMigration Load (5.4ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Migrating to ReplaceDepositConfirmationsWithMinConfirmations (20180718113111)
== 20180718113111 ReplaceDepositConfirmationsWithMinConfirmations: migrating ==
  ReplaceDepositConfirmationsWithMinConfirmations::Currency Load (7.4ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`type` = 'coin'  ORDER BY `currencies`.`id` ASC LIMIT 1000
   (0.6ms)  BEGIN
   (0.5ms)  COMMIT
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `[]' for nil:NilClass

**Comment by shal** [comment]
@champmine Seems like it is not related to workbench, but to peatio.
