### ISSUE TITLE
Update height problem

### ISSUE THREAD

**Issue by UfukAntep** [rubykube/workbench#268]
Hello,
I don't see the ethereum I sent. I think that's the problem. "After deployment, height of blockchains should be updated to start receiving deposits. Go to Blockchains Tab in Peatio Admin Panel and update height" I need to use the place in the picture, right? But it doesn't work. Is my field wrong?

![alt text](https://u-chest.com/wp-content/uploads/2018/12/bumu.png)

**Comment by shal** [comment]
Hi @UfukAntep

Height should be updated in peatio admin panel, not it rinkeby website.

**Comment by UfukAntep** [comment]
I'm doing it from the peatio panel. Am I copying the right place? That's why I added a picture.

**Comment by UfukAntep** [comment]
Thank you. Should I update every day? Because I'm working in a development environment.

**Comment by shal** [comment]
Man, it updated by blockchain daemon!
