### ISSUE TITLE
Transaction successful but doesn't look ethereum local

### ISSUE THREAD

**Issue by UfukAntep** [rubykube/workbench#281]
Transaction successful but doesn't look ethereum local. Please see the 2 pictures below

![alt text](https://i.imgyukle.com/2019/01/04/1Jsr0.png)

![alt text](https://i.imgyukle.com/2019/01/04/1Jplx.png)

**Comment by Guillerbr** [comment]
There is another topic on this should be a bug that I still can not identify, we will try to look at the ruby code where this is done and seek the cause. But we need other heads in this game.

**Comment by UfukAntep** [comment]
Are there errors in the project you are using? Can you upload if there is no error?

**Comment by AkashiHidaka** [comment]
Hello UfukAntep 
I have the same error and no add balance and not show ethereum.
So you solve this error?

**Comment by UfukAntep** [comment]
Hello, AkashiHidaka,

I'm sorry for the late reply. I still can't solve the error. (Geth rinkeby is synchronized) Can the panel not show the rinkeby network?

**Comment by AkashiHidaka** [comment]
I using real network and deposit correctly work and no working of withdraw part.

**Comment by UfukAntep** [comment]
Is your real network balance appearing in this image?

I am using this command for rinkeby -> `geth --rinkeby --rpc --rpcaddr "127.0.0.1"`

What command do you run for geth?


![alt text](https://camo.githubusercontent.com/704aa51a90e705a0900ed06802fb8b24180367e5/68747470733a2f2f692e696d6779756b6c652e636f6d2f323031392f30312f30342f314a7372302e706e67)

**Comment by UfukAntep** [comment]
What command do you run for real network? 
I am using this command for rinkeby -> `geth --rinkeby --rpc --rpcaddr "0.0.0.0"`

How did you change this screen?

![alt text](https://i.imgyukle.com/2019/02/27/lmJd1.png)

**Comment by UfukAntep** [comment]
@AkashiHidaka  ?
