### ISSUE TITLE
Cannot sign in. 

### ISSUE THREAD

**Issue by hasanaliqureshi** [rubykube/workbench#290]
![image](https://user-images.githubusercontent.com/12941929/52540992-cb03dc80-2db1-11e9-8f2d-baa870bf7b6e.png)

Can't login too.

http://auth.inspon.com/oauth/authorize?client_id=a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4&redirect_uri=http%3A%2F%2Fapi.inspon.com%2Fauth%2Fbarong%2Fcallback&response_type=code&state=a526d51d8e71927be24d600039ad28f35106dac72290611a

_Originally posted by @hasanaliqureshi in https://github.com/rubykube/workbench/issues/60#issuecomment-462188909_

**Comment by hasanaliqureshi** [comment]
Fixed it.
redirect uri on database was wrong.
changed it using pma subdomain.

**Comment by mur-wtag** [comment]
@hasanaliqureshi what would the redirect uri and in which table I should update it?

**Comment by phuong17889** [comment]
> Fixed it.
> redirect uri on database was wrong.
> changed it using pma subdomain.

you save my life
