### ISSUE TITLE
ArgumentError in WelcomeController#index on MACOS

### ISSUE THREAD

**Issue by hashingitout** [rubykube/workbench#34]
ArgumentError in WelcomeController#index
Base fiat currency is not specified.

![action controller exception caught](https://user-images.githubusercontent.com/35281862/37507205-bf22f3ae-28c3-11e8-994b-acc9fef9618a.png)

help please! On a Mac

**Comment by antonror** [comment]
@hashingitout Hi! It means that you have 0 currencies in your database (probably rake db:seeds failed upon setup). Do the following, assuming you are running a docker container: 

1. do `docker ps` this will display your running docker containers. 
2. copy id of peatio container 
![selection_009](https://user-images.githubusercontent.com/20702462/37509650-db8c3266-2900-11e8-909e-e41317afec6e.png)
3. run `docker exec -it 21583144f2cc /bin/bash` with your container id insted of this one
4. now you are inside application folder of docker container, simply launch 
`rake db:reset` it will recreate database properly

**Comment by hashingitout** [comment]
Thank you but i get

OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "chdir to cwd (\"/home/app\") set in config.json failed: no such file or directory": unknown

**Comment by antonror** [comment]
@hashingitout looks like some earlier steps were missed. There's a config option which puts you inside `/home/app` folder when launching `bash`. Now the error tells you that there's no `/home/app` directory inside a container. Please make sure that containers were setup and built properly

**Comment by antonror** [comment]
@hashingitout are you using windows? then just try:
`docker exec -it <container-id> /bin/sh` instead of `docker exec -it <container-id> /bin/bash`

**Comment by hashingitout** [comment]
@antonror Where can i find more info on the config option which puts you inside /home/app ?

**Comment by antonror** [comment]
@hashingitout please reach https://github.com/rubykube 
my docker build works flawlessly on Ubuntu with docker and docker-compose

**Comment by hashingitout** [comment]
I have tried on ubuntu as well. I am getting the same error.

**Comment by hashingitout** [comment]
This is what I am doing:

Clone peatio and barong and workbench to ~/Development/
in workbench directory: make build
Then: make prepare. 
Then: make setup-apps
Edit /etc/hosts: 0.0.0.0 peatio	0.0.0.0 barong

Start barong: docker-compose up -d barong
Start peatio server: docker-compose up -d peatio

**Comment by hashingitout** [comment]
Fixed With:

docker-compose run --rm peatio "rake db:reset"
docker-compose run --rm peatio "rake db:migrate"
