### ISSUE TITLE
Update workbench to support upcoming Peatio 1.5 features (trading UI extraction)

### ISSUE THREAD

**Issue by yivo** [rubykube/workbench#35]
https://github.com/rubykube/peatio/commit/8a7daee6cdea75001759ddfc4a70851a76392510

**Comment by yivo** [comment]
Please, check TravisCI script to find out how does this work. The trading UI repo lives at https://github.com/rubykube/peatio-trading-ui.

All the questions could be answered by me and by @yssavchuk.

**Comment by nchigwamba** [comment]
@yivo / @yssavchuk, I just submitted a PR for this. See https://github.com/rubykube/workbench/pull/40.
