### ISSUE TITLE
Barong issue

### ISSUE THREAD

**Issue by franklee1** [rubykube/workbench#36]
I get  this error 
![image](https://user-images.githubusercontent.com/34935403/37654346-957cbd34-2c63-11e8-8ef2-eceadd44948c.png)

Once I try to sign in with admin@barong.io at http://barong:8001/

**Comment by zyfu90** [comment]
Same here, couldn't get it fixed

**Comment by feiyan-cs** [comment]
I have the same issue. Why is it happening?
