### ISSUE TITLE
Cannot successfully set up peatio

### ISSUE THREAD

**Issue by feiyan-cs** [rubykube/workbench#39]
I keep getting these errors. Is it the same error as #22 ?

`
error Could not write file "/home/app/yarn-error.log": "EACCES: permission denied, open '/home/app/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/app/vendor/assets/yarn_components'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: EACCES: permission denied, open '/home/app/.yarnrc'

=== Removing old logs and tempfiles ===
mkdir -p tmp/sessions
rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - tmp

Tasks: TOP => tmp:create => tmp/sessions
(See full trace by running task with --trace)

=== Setup database ===
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
/home/app/config/initializers/assets.rb:29:in `chdir'
/home/app/config/initializers/assets.rb:29:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/app/config/environment.rb:5:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

=== Creating liability proofs ===
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
/home/app/config/initializers/assets.rb:29:in `chdir'
/home/app/config/initializers/assets.rb:29:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/app/config/environment.rb:5:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => solvency:liability_proof => environment
(See full trace by running task with --trace)
docker-compose run --rm barong "./bin/setup"
Starting workbench_db_1 ... done
`/home/app` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.

== Removing old logs and tempfiles ==

== Preparing database ==
cp: cannot create regular file 'config/database.yml': Permission denied

== Command ["cp config/database.yml.example config/database.yml"] failed ==
Makefile:12: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1

`

**Comment by martianatwork** [comment]
I fixed this by using
`chmod 777 -R *` 
in workbench directory

**Comment by sg552** [comment]
I met this issue when using "un root" user, and met permission problems 

solution is quite simple, run the command with sudo.
