### ISSUE TITLE
Using docker local volumes for development?

### ISSUE THREAD

**Issue by kriskelly** [rubykube/workbench#43]
This may seem obvious, but I had assumed this would set up a dev environment that would allow me to make changes to the peatio and barong apps if it turns out that I need to fork those for some reason. Typically for development with docker I use volumes that map the local application directory to the container in order to make changes without having to rebuild each time. I can't seem to do that here because there are a bunch of build artifacts that get overwritten when I mount the volume. For instance, all of the packages installed via Yarn.

How do you all set up your environment for development? I'm not dead set on forking this software but I've already had to make some changes to the Twilio config to work around some errors with Barong phone number verification the first time I use Barong. That's probably a separate issue that could be addressed in another ticket though.

**Comment by umaimehm** [comment]
I agree. The development guide is misleading. It does not set up a development environment. This is just a running instance.

One way this could be done is to run dependent modules as containers and run peatio and barong locally with puma.
OR mirror your hard disk with docker images (not the preffered approach)
