### ISSUE TITLE
Issue after setup  Your account has been disabled, contact admin if you have any problem.

### ISSUE THREAD

**Issue by Nolaan** [rubykube/workbench#49]
Hello,
After running `make run` I've the following issue where I can't log into peatio with barong : 
![screenshot_20180419_114858](https://user-images.githubusercontent.com/3602244/38984766-de3024a0-43c7-11e8-8a11-e6b1f02e7df5.png)

**Comment by robi772** [comment]
For me same error have. :(

**Comment by Nolaan** [comment]
Up the same with the docker images!!!

**Comment by dsuwirya** [comment]
Same here, any help please ?

**Comment by appsdev9** [comment]
I experienced the error. Nothing can do.

**Comment by ZohairZaman** [comment]
same

**Comment by nuyulcore** [comment]
Same error with me

**Comment by shal** [comment]
Hi,

Visit `auth.wb.local`. 

Authenticate using 

```
Email: admin@barong.io
Password: Qwerty123
```

Then you need manually create labels in barong admin panel for your admin user.
