### ISSUE TITLE
Cannot sign in with barong

### ISSUE THREAD

**Issue by rojermaharjan** [rubykube/workbench#60]
I have setup the application as instructed but I'm getting this error after clicking sign in with barong.

![image](https://user-images.githubusercontent.com/10989068/39348928-cfdc1d94-4a18-11e8-8d6b-81eac6796dde.png)

It redirects me to http://192.168.1.143:8001/oauth/authorize?client_id=a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4&redirect_uri=http%3A%2F%2F192.168.1.143%2Fauth%2Fbarong%2Fcallback&response_type=code&state=bd6647482f42a1ac4c5523529ce80739eb198597b3ef7701 after clicking the button.

What did I miss?

**Comment by wenewzhang** [comment]
i got the same problem,use [](http://barong:8001/oauth/applications) to login,
in ur situation,it's  http://192.168.1.143:8001/oauth/applications

**Comment by uguracar** [comment]
I was able to login to URL http://IP:8001/admin with admin@barong.io account

**Comment by appsdev9** [comment]
What is the default password of admin account?

Thanks

**Comment by ashanaakh** [comment]
@rojermaharjan you should login to `auth.wb.local`.

Default credentials are:

Email: `admin@barong.io`
Password: `Qwerty123`

**Comment by hasanaliqureshi** [comment]
![image](https://user-images.githubusercontent.com/12941929/52540992-cb03dc80-2db1-11e9-8f2d-baa870bf7b6e.png)

Can't login too.

http://auth.inspon.com/oauth/authorize?client_id=a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4&redirect_uri=http%3A%2F%2Fapi.inspon.com%2Fauth%2Fbarong%2Fcallback&response_type=code&state=a526d51d8e71927be24d600039ad28f35106dac72290611a

**Comment by blopezmontalvo** [comment]
A mi me pasa lo mismo cuando cambie de dominio. Pudieron solucionarlo.
