### ISSUE TITLE
make run ERROR

### ISSUE THREAD

**Issue by auvilink** [rubykube/workbench#68]
I run "vagrant up" under "workbench" folder.

Then "sudo make build", "sudo make run"

ERROR: for compose_barong_1  Cannot start service barong: driver failed programming external connectivity on endpoint compose_barong_1 (1564a3e5397a8fdb867838c0751dd857790ea33e463166c168d478c60184bd56): Error starting userland proxy: listen tcp 0.0.0.0:8001: bind: address already in use

ERROR: for barong  Cannot start service barong: driver failed programming external connectivity on endpoint compose_barong_1 (1564a3e5397a8fdb867838c0751dd857790ea33e463166c168d478c60184bd56): Error starting userland proxy: listen tcp 0.0.0.0:8001: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Makefile:15: recipe for target 'setup-apps' failed

Thanks.

**Comment by ianeinser** [comment]
there is a bug.. check scripts/install_workbench.sh and comment systemctl enable nginx with #.

**Comment by shal** [comment]
Hi @auvilink,
We are not currentcly support vagrant.
