### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by fouvy** [rubykube/workbench#71]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'rubykube/workbench'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'rubykube/workbench' is up to date...
==> default: Setting the name of the VM: workbench_default_1526055930037_77357
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 8001 (guest) => 8001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
/usr/lib/ruby/vendor_ruby/net/ssh.rb:194:in `start': invalid option(s): verify_host_key (ArgumentError)
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/plugins/communicators/ssh/communicator.rb:423:in `block (2 levels) in connect'
	from /usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/plugins/communicators/ssh/communicator.rb:397:in `block in connect'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/plugins/communicators/ssh/communicator.rb:396:in `connect'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/plugins/communicators/ssh/communicator.rb:84:in `block in wait_for_ready'
	from /usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/plugins/communicators/ssh/communicator.rb:62:in `wait_for_ready'
	from /tmp/.mount_vagranx5A00N/usr/gembundle/gems/vagrant-2.1.1/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'

**Comment by c0sco** [comment]
You don't mention what OS you're on but I had this problem using the 2.1.1 zip on Ubuntu 16.04. Switching to the 2.1.1 deb fixed it (see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890662).

**Comment by shudipta** [comment]
I had the same problem and it was solved for your suggestion @c0sco.

**Comment by shal** [comment]
Sorry guys, this is outdated, we are supporting vagrant anymore.
