### ISSUE TITLE
Password of admin@barong.io

### ISSUE THREAD

**Issue by appsdev9** [rubykube/workbench#73]
Hi,

I could not find the password of admin@barong.io

I tried the below, but it could not find the suitable configuration file. Please help. Thanks.
1. Start barong: docker-compose up -d barong
2. Create admin user for barong: docker-compose run --rm barong bin/rake db:seed It will output password for admin@barong.io

**Comment by jianbosu** [comment]
hi,do you got the password? I have the same problem
![_20180531134328](https://user-images.githubusercontent.com/17507066/40763820-d6345f50-64d8-11e8-8cff-43fea0d6c242.png)
