### ISSUE TITLE
Replace db:setup to db:create db:migrate db:seed

### ISSUE THREAD

**Issue by yivo** [rubykube/workbench#74]
See this issue for explanations: https://github.com/rubykube/peatio/issues/1104

**Comment by mod** [comment]
@dkkoval can you make the change ?

**Comment by shal** [comment]
https://github.com/rubykube/workbench/blob/148a7dd006bf0c85150a93e79bd9fe29d65c2abd/Makefile#L21

Closed.

**Comment by ianeinser** [comment]
@shal unfortunately it doesn't work db:create fails since the db cannot be created. Please refer to #113
