### ISSUE TITLE
Peatio account disabled, contact admin

### ISSUE THREAD

**Issue by ZohairZaman** [rubykube/workbench#75]
I have followed all the stops to set the workbench up, but when I try to log in with peatio, i keep getting the following error:
Your account has been disabled, contact admin if you have any problem.

Any help?

**Comment by nuyulcore** [comment]
I had the same issues. Is Everyone already fixing it?

**Comment by JaapHaitsma** [comment]
I got it to work by going into mysql database barong_development and then set the level of the account admin@barong.io to 3 and state to active

**Comment by ashanaakh** [comment]
Duplicated #97.

**Comment by ashanaakh** [comment]
Duplicate #97.
