### ISSUE TITLE
BTC Address Generation Not Functional

### ISSUE THREAD

**Issue by jdowning100** [rubykube/workbench#77]
Moved from [(Peatio)#1182](https://github.com/rubykube/peatio/issues/1182)

Hi, I have tried to get help in the telegram for this issue to no avail. This may be an issue caused by workbench, as other people have gotten this to work when building from source.
I am running the latest master workbench with Peatio v1.8 and cannot generate a deposit address with Peatio. Right now I am trying to set up BTC deposits.
Here you can see the issue:

![deposit](https://user-images.githubusercontent.com/26939949/40444007-bb52d546-5e8d-11e8-9e3e-561efef01929.PNG)

The deposit address is blank. When I try to copy it I copy nothing. There are no script errors in the console.
The following is my workbench/config/peatio/currencies.yml file:

![currency](https://user-images.githubusercontent.com/26939949/40444207-5342230c-5e8e-11e8-9744-249ee970dd3c.PNG)

The following is my database entry for BTC:

![btc](https://user-images.githubusercontent.com/26939949/40444533-3cdc9970-5e8f-11e8-801d-22c9a5f3cb03.PNG)

I have tried almost everything to get the deposit addresses working. I have dropped and reseeded the database, restarted the server, changed the currency settings in the database, checked to make sure pusher is working, god daemons are up, etc.
Strangely, god does not log anything when I navigate to the BTC deposit page.

![deposit_coin](https://user-images.githubusercontent.com/26939949/40444336-b8e9fcde-5e8e-11e8-8a41-0d028e9d60bb.PNG)

But god is up:

![god](https://user-images.githubusercontent.com/26939949/40444518-3231574a-5e8f-11e8-8f90-bbdbc2244adb.PNG)

And my RPC server is up and can generate an address:

![curl](https://user-images.githubusercontent.com/26939949/40444557-4f8f2d1c-5e8f-11e8-81e3-7b03f50e8b91.PNG)

So, what am I doing wrong? What do I have to do to generate a simple deposit address?

Update: I originally posted this to the rubykube/peatio repo. I have built Peatio 1-8-stable from source and address generation is working. Therefore this is an issue with workbench or docker. I have moved this issue from rubykube/peatio to rubykue/workbench.

**Comment by ashanaakh** [comment]
Closed via https://github.com/rubykube/peatio/issues/1182

**Comment by rraallvv** [comment]
@jdowning100 I'm having this issue with Peatio 1-8-stable, all daemons seem to be working, and I can create an address with jsonrpc. Still Peatio is not showing the generated addresses, nor showing any error on the logs.

```
$ god status
amqp:deposit_coin: up
amqp:deposit_coin_address: up
amqp:market_ticker: up
amqp:matching: up
amqp:order_processor: up
amqp:pusher_market: up
amqp:pusher_member: up
amqp:slave_book: up
amqp:trade_executor: up
amqp:withdraw_coin: up
coins: up
global_state: up
hot_wallets: up
k: up
payment_transaction: up
websocket_api: up
withdraw_audit: up
```

```
$ curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnewaddress", "params": [] }' -H 'content-type: text/plain;' http://usert:password@localhost:8332
{"result":"37q6EnJdWg7jWFhJQdg4YGoxbWnm4CTqKM","error":null,"id":"curltest"}
```

**Comment by rraallvv** [comment]
By the way, would this issue have to do with whether `URL_SCHEME` and `FORCE_SECURE_CONNECTION` are `https` and `'true'` respectively in `config/application.yml`? Where can I see if the bitcoin daemon is receiving those jsonrpc requests?

**Comment by Joan1590** [comment]
Hi !, I installed this code,

I Can Solved your Questions, The problem with bitcoin is, cause the rpc no allow your docker IP, then, you need add the IP to the bitcoin.conf,

example: 

printtoconsole=1

server=1
listen=1
daemon=1

rpcallowip=172.18.0.255/0
rpcuser=admin
rpcpassword=changeme

@rraallvv 
@jdowning100

**Comment by rraallvv** [comment]
@Joan1590 Thanks. Although in my case I think that's not what causes the problem, I can get a new address using curl, both, with BTC and also with ETH via JSONRPC.

**Comment by Joan1590** [comment]
@rraallvv the IP for docker is different that your VPS or your Server, you can see the docker log, with that command "docker logs workbench_deposit_coin_address_1" 
i see the error 403 in there, I guess that is.

**Comment by rraallvv** [comment]
Can you check if the request was made via HTTPS?

I'm suspecting the 403 responce has to do with option `config.force_ssl` in `config/environments/production.rb` and the environment var `FORCE_SECURE_CONNECTION` because in my case it's working with `RAILS_ENV=development`

**Comment by rraallvv** [comment]
Hmm... thanks, I'll take a closer look to the logs then. I was enable to enable the logger for production too.

**Comment by asadhayat1068** [comment]
Having the same problem. Have you guys solved this??
