### ISSUE TITLE
account disabled message when logging into peatio

### ISSUE THREAD

**Issue by JaapHaitsma** [rubykube/workbench#97]
I followed instructions on the homepage but when I then login with barong I get a message that the account is disabled. How can I enable it?

**Comment by ashanaakh** [comment]
Hi @JaapHaitsma,

You should manually create 3 labels in the barong admin page.

Labels:

```
email:verified scope "private"=> account level 1
phone:verified scope "private"=> account level 2
document:verified scope "private"=> account level 3
```

Unfortunately, barong have issue with seeding third level user.
